name: r_dart
version: 0.3.0
description: Generate colors images and other assets as String.

homepage: https://github.com/zhouchaohong1111/R.dart
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: '>=0.12.1 <2.0.0'
  dart_style: ^1.0.0
  path: '>=0.9.0 <2.0.0'
  yaml: ^2.1.15
  recase: ^2.0.1
  build: ^1.1.4
  build_config: ^0.4.0

  #
#  build_runner: ^1.7.4
#  source_gen: ^0.9.0

dev_dependencies:
  test: any
  build_test: any
  lint: ^1.0.0
